// Targeted by JavaCPP version 1.5.1: DO NOT EDIT THIS FILE
package icu.ootime.jwintoast.global

import icu.ootime.jwintoast.presets.WinToastLib
import org.bytedeco.javacpp.Loader

object WinToastLib : WinToastLib() {
    init {
        Loader.load()
    }
}